import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState,useEffect } from 'react'
import Pusher from "pusher-js";
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [username,setUsername] = useState("");
  const [message,setMessage] = useState("");
  const [messages,setMessages] = useState([]);
  let allMessages = [];
  useEffect(()=>{
    Pusher.logToConsole = true;

    var pusher = new Pusher('5b01f399fafc2a596313', {
      cluster: 'eu'
    });

    var channel = pusher.subscribe('chichat');
    channel.bind('message', function(data) {
      allMessages.push(data)
      setMessages(allMessages);
      alert(JSON.stringify(data));
    });
  });
  const sendMessage = async (e) => {
    e.preventDefault();
    await fetch("http://localhost:8000/api/messages",{
      method:"POST",
      headers:{'Content-Type':'application/json'},
      body:JSON.stringify({
        username,
        message
      })
    });
    setMessage('');
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"/>
      </Head>
      <main className={styles.main}>
        <div>
          <input type="text" value={username} onChange={(e)=>{setUsername(e.target.value)}}/>
        </div>
        {messages.map((message)=>(
          <div class="list-group list-group-flush border-bottom scrollarea">
            <div  class="list-group-item list-group-item-action py-3 lh-sm">
              <div class="d-flex w-100 align-items-center justify-content-between">
                <strong class="mb-1">{message.username}: {message.message}</strong>
                {/* <small class="text-muted">Tues</small> */}
              </div>
            </div>
          </div>
        ))}
        <div>
          <input type="text" value={message} onChange={(e)=>{setMessage(e.target.value)}}/>
          <button onClick={(e)=>{sendMessage(e)}}>Send</button>
        </div>
      </main>
      </>
  )
}
